import os
import pandas as pd
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt

# Page Configurations
st.set_page_config(
    page_title="Enterprise Supply Chain Demand & Inventory Engine",
    page_icon="💼",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Dark Mode & Glassmorphism Styling Injection
st.markdown("""
    <style>
    .main {
        background-color: #090d16;
        color: #f3f4f6;
    }
    div[data-testid="stMetricValue"] {
        font-size: 28px;
        font-weight: 700;
        color: #86efac;
    }
    div[data-testid="stMetricLabel"] {
        font-size: 13px;
        color: #9ca3af;
        font-weight: 500;
    }
    .metric-card {
        background: rgba(17, 25, 40, 0.75);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 12px;
        padding: 20px;
        text-align: center;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    }
    .status-badge {
        padding: 4px 8px;
        border-radius: 6px;
        font-size: 12px;
        font-weight: 600;
    }
    .status-reorder {
        background-color: rgba(239, 68, 68, 0.2);
        color: #ef4444;
        border: 1px solid #ef4444;
    }
    .status-healthy {
        background-color: rgba(34, 197, 94, 0.2);
        color: #22c55e;
        border: 1px solid #22c55e;
    }
    .status-over {
        background-color: rgba(59, 130, 246, 0.2);
        color: #3b82f6;
        border: 1px solid #3b82f6;
    }
    </style>
""", unsafe_allow_html=True)

# File Paths
DATA_DIR = r"C:\Users\amanl\.gemini\antigravity\scratch\supply-chain-optimization"
PRODUCT_METADATA_PATH = os.path.join(DATA_DIR, "product_metadata.csv")
FORECAST_METRICS_PATH = os.path.join(DATA_DIR, "forecast_metrics.csv")
PREDICTIONS_PATH = os.path.join(DATA_DIR, "predictions.csv")
SIMULATION_RESULTS_PATH = os.path.join(DATA_DIR, "simulation_results.csv")

# Dynamic z-score calculator helper
def get_z_score(service_level):
    levels = {80.0: 0.842, 85.0: 1.036, 90.0: 1.282, 95.0: 1.645, 98.0: 2.054, 99.0: 2.326, 99.9: 3.090}
    closest = min(levels.keys(), key=lambda x: abs(x - service_level))
    return levels[closest]

@st.cache_data
def load_data():
    """Loads all data files generated by pipeline and models."""
    if not (os.path.exists(PRODUCT_METADATA_PATH) and os.path.exists(FORECAST_METRICS_PATH) and os.path.exists(PREDICTIONS_PATH)):
        return None, None, None
        
    meta = pd.read_csv(PRODUCT_METADATA_PATH)
    metrics = pd.read_csv(FORECAST_METRICS_PATH)
    preds = pd.read_csv(PREDICTIONS_PATH)
    preds["Date"] = pd.to_datetime(preds["Date"])
    
    return meta, metrics, preds

# --- SIDEBAR CONTROL CENTER ---
st.sidebar.markdown("""
    <div style='text-align: center; margin-bottom: 20px;'>
        <h2 style='font-family: Outfit; color: #86efac; margin-bottom: 4px;'>Deloitte</h2>
        <p style='color: #9ca3af; font-size: 12px; text-transform: uppercase; letter-spacing: 0.1em;'>Supply Chain & AI Practice</p>
    </div>
""", unsafe_allow_html=True)

st.sidebar.header("🔧 Simulation Controls")

meta_df, metrics_df, preds_df = load_data()

if meta_df is None:
    st.error("[-] Engine data files not detected. Run run_setup.ps1 first to generate modeling datasets!")
    st.stop()

# 1. Target Service Level Slider
service_level = st.sidebar.slider(
    "🎯 Target Service Level (%)",
    min_value=80.0,
    max_value=99.9,
    value=95.0,
    step=5.0,
    help="Higher service level guarantees fewer stockouts but increases holding costs."
)

# 2. Lead Time Modifier
lt_modifier = st.sidebar.slider(
    "⏱️ Lead Time Modifier (Days)",
    min_value=-2,
    max_value=3,
    value=0,
    help="Simulates longer supplier delays or logistics optimizations."
)

# 3. Holding Cost Modifier
hc_modifier = st.sidebar.slider(
    "💵 Holding Cost Modifier (%)",
    min_value=-50,
    max_value=100,
    value=0,
    help="Adjusts warehousing rental rates or capital costs."
)

# Select SKU to Inspect
top_skus = meta_df["StockCode"].tolist()
selected_sku = st.sidebar.selectbox("📦 Inspect Product SKU", top_skus, format_func=lambda x: f"{x} - {meta_df[meta_df['StockCode'] == x]['Description'].iloc[0]}")

# --- RE-RUN INVENTORY OPTIMIZER DYNAMICALLY ---
# We compute inventory parameters dynamically based on sidebar user modifications
z_score = get_z_score(service_level)
sku_meta = meta_df[meta_df["StockCode"] == selected_sku].iloc[0]
sku_metrics = metrics_df[metrics_df["StockCode"] == selected_sku].iloc[0]
sku_preds = preds_df[preds_df["StockCode"] == selected_sku].copy().sort_values("Date")

# Apply Modifiers
adjusted_lead_time = max(1, int(sku_meta["LeadTime"]) + lt_modifier)
adjusted_holding_cost = max(0.001, float(sku_meta["HoldingCostDaily"]) * (1 + hc_modifier/100))
stockout_penalty = float(sku_meta["StockoutPenalty"])
uncertainty = float(sku_metrics["Uncertainty"])

# Re-simulate optimized safety stock
ml_ss = z_score * uncertainty * np.sqrt(adjusted_lead_time)

# Main Title Header
st.markdown("""
    <div style='background: linear-gradient(135deg, rgba(34, 197, 94, 0.1) 0%, rgba(59, 130, 246, 0.05) 100%); padding: 24px; border-radius: 16px; border: 1px solid rgba(255, 255, 255, 0.08); margin-bottom: 28px;'>
        <h1 style='font-family: Outfit; font-weight: 800; color: #fff; margin-bottom: 6px;'>Enterprise Supply Chain Demand & Inventory Engine</h1>
        <p style='color: #9ca3af; margin-bottom: 0;'><span style='color: #86efac; font-weight: 600;'>Consulting Case Study:</span> Machine Learning Predictive Safety Stock vs. Historical Baseline Replenishment</p>
    </div>
""", unsafe_allow_html=True)

# Run complete simulation metrics for all SKUs dynamically to update KPI metrics
all_sim_records = []
total_baseline_cost = 0.0
total_ml_cost = 0.0
total_stockouts_baseline = 0
total_stockouts_ml = 0

for _, row in meta_df.iterrows():
    sku = row["StockCode"]
    sku_m = metrics_df[metrics_df["StockCode"] == sku].iloc[0]
    sku_p = preds_df[preds_df["StockCode"] == sku].copy().sort_values("Date")
    
    # Run rapid standard daily simulator for statistics
    actuals = sku_p["Demand"].values
    predictions = sku_p["Predicted"].values
    
    lt = max(1, int(row["LeadTime"]) + lt_modifier)
    hc = max(0.001, float(row["HoldingCostDaily"]) * (1 + hc_modifier/100))
    pen = float(row["StockoutPenalty"])
    unc = float(sku_m["Uncertainty"])
    
    # Calculate safety stocks
    std_hist = actuals.std()
    b_ss = 1.5 * std_hist * np.sqrt(lt)
    m_ss = z_score * unc * np.sqrt(lt)
    
    # Fast simulator logic
    def run_fast_sim(policy):
        inv = 100
        hold = 0.0
        stock = 0.0
        scount = 0
        pending = []
        
        b_rop = (actuals.mean() * lt) + b_ss
        b_qty = max(50, actuals.mean() * 14)
        
        for d in range(len(actuals)):
            # Arrive orders
            inv += sum(o["qty"] for o in pending if o["eta"] == d)
            pending = [o for o in pending if o["eta"] != d]
            
            dem = actuals[d]
            if inv >= dem:
                inv -= dem
            else:
                unf = dem - inv
                inv = 0
                scount += 1
                stock += unf * pen
                
            hold += inv * hc
            eff = inv + sum(o["qty"] for o in pending)
            
            if policy == "baseline":
                if eff <= b_rop:
                    pending.append({"eta": d + lt, "qty": b_qty})
            else:
                m_rop = (predictions[d] * lt) + m_ss
                m_qty = max(50, predictions[d] * 14)
                if eff <= m_rop:
                    pending.append({"eta": d + lt, "qty": m_qty})
                    
        return hold, stock, scount, inv
        
    b_h, b_s, b_c, b_final_inv = run_fast_sim("baseline")
    m_h, m_s, m_c, m_final_inv = run_fast_sim("ml")
    
    total_baseline_cost += (b_h + b_s)
    total_ml_cost += (m_h + m_s)
    total_stockouts_baseline += b_c
    total_stockouts_ml += m_c
    
    # Append for reorder decision matrix
    all_sim_records.append({
        "StockCode": sku,
        "Description": row["Description"],
        "UnitPrice": round(float(row["UnitPrice"]), 2),
        "SafetyStock": int(m_ss),
        "ROP": int((predictions[-1] * lt) + m_ss),
        "CurrentInventory": int(m_final_inv)
    })

cost_saved = total_baseline_cost - total_ml_cost
pct_saved = (cost_saved / max(1.0, total_baseline_cost)) * 100
stockout_reduction = ((total_stockouts_baseline - total_stockouts_ml) / max(1, total_stockouts_baseline)) * 100

# --- KPI METRIC CARDS ---
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Total Operational Savings", f"${cost_saved:,.2f}", f"{pct_saved:.1f}% vs Baseline")
with col2:
    st.metric("Stockout Incidence Cuts", f"-{total_stockouts_baseline - total_stockouts_ml} Days", f"{stockout_reduction:.1f}% reduction")
with col3:
    st.metric("ML Optimized Safety Stock", f"{int(ml_ss)} Units", f"z = {z_score:.3f}")
with col4:
    st.metric("Model Prediction MAPE", f"{sku_metrics['MAPE']}%", f"R² = {sku_metrics['R2']:.2f}")

st.write("---")

# --- CHARTS AND VISUALISATIONS ---
col_left, col_right = st.columns([1, 1])

with col_left:
    st.subheader(f"📈 30-Day Demand Forecast: SKU [{selected_sku}]")
    st.write(f"*{sku_meta['Description']}*")
    
    # Generate demand forecast vs actuals plot
    fig, ax = plt.subplots(figsize=(10, 5), facecolor='#090d16')
    ax.set_facecolor('#0b132b')
    
    dates = sku_preds["Date"].dt.strftime('%b %d')
    actuals = sku_preds["Demand"].values
    forecast = sku_preds["Predicted"].values
    lower = sku_preds["Lower_Bound"].values
    upper = sku_preds["Upper_Bound"].values
    
    ax.plot(dates, actuals, label="Actual Daily Demand", color="#3b82f6", linewidth=2, marker='o', markersize=4)
    ax.plot(dates, forecast, label="XGBoost ML Forecast", color="#86efac", linewidth=2.5, linestyle='--')
    ax.fill_between(dates, lower, upper, color="#86efac", alpha=0.12, label="95% Prediction Interval")
    
    ax.tick_params(colors='#9ca3af', labelsize=9)
    ax.xaxis.set_major_locator(plt.MaxNLocator(8))
    ax.set_ylabel("Quantity Sold", color="#9ca3af", fontsize=10)
    ax.grid(True, color="#1e293b", linestyle=':', alpha=0.5)
    
    # Styling Legend
    leg = ax.legend(facecolor='#090d16', edgecolor='none')
    for text in leg.get_texts():
        text.set_color('#f3f4f6')
        
    plt.xticks(rotation=30)
    plt.tight_layout()
    st.pyplot(fig)

with col_right:
    st.subheader("📊 Dynamic Simulated Daily Inventory Levels")
    st.write("ML-Optimized Safety Stock policy preventing stockouts vs. Historical baseline exhaustion.")
    
    # Generate simulated inventory curve
    # Re-run simulation dynamically to log daily inventory
    actuals_arr = sku_preds["Demand"].values
    forecast_arr = sku_preds["Predicted"].values
    
    std_hist = actuals_arr.std()
    b_ss = 1.5 * std_hist * np.sqrt(adjusted_lead_time)
    b_rop = (actuals_arr.mean() * adjusted_lead_time) + b_ss
    b_qty = max(50, actuals_arr.mean() * 14)
    
    # Simulated trace
    def get_inv_trace(policy):
        inv = 100
        trace = []
        pending = []
        for d in range(len(actuals_arr)):
            inv += sum(o["qty"] for o in pending if o["eta"] == d)
            pending = [o for o in pending if o["eta"] != d]
            
            dem = actuals_arr[d]
            inv = max(0, inv - dem)
            trace.append(inv)
            
            eff = inv + sum(o["qty"] for o in pending)
            if policy == "baseline":
                if eff <= b_rop:
                    pending.append({"eta": d + adjusted_lead_time, "qty": b_qty})
            else:
                m_rop = (forecast_arr[d] * adjusted_lead_time) + ml_ss
                m_qty = max(50, forecast_arr[d] * 14)
                if eff <= m_rop:
                    pending.append({"eta": d + adjusted_lead_time, "qty": m_qty})
        return trace

    baseline_trace = get_inv_trace("baseline")
    ml_trace = get_inv_trace("ml")
    
    fig2, ax2 = plt.subplots(figsize=(10, 5), facecolor='#090d16')
    ax2.set_facecolor('#0b132b')
    
    ax2.plot(dates, baseline_trace, label="Baseline Inventory", color="#ef4444", linewidth=2)
    ax2.plot(dates, ml_trace, label="ML Optimized Inventory", color="#22c55e", linewidth=2)
    
    # Reorder thresholds
    ax2.axhline(y=b_rop, color="#ef4444", linestyle=':', alpha=0.5, label="Baseline ROP")
    ax2.axhline(y=(forecast_arr[-1]*adjusted_lead_time)+ml_ss, color="#22c55e", linestyle=':', alpha=0.5, label="ML ROP")
    
    ax2.tick_params(colors='#9ca3af', labelsize=9)
    ax2.xaxis.set_major_locator(plt.MaxNLocator(8))
    ax2.set_ylabel("Units On-Hand", color="#9ca3af", fontsize=10)
    ax2.grid(True, color="#1e293b", linestyle=':', alpha=0.5)
    
    leg2 = ax2.legend(facecolor='#090d16', edgecolor='none')
    for text in leg2.get_texts():
        text.set_color('#f3f4f6')
        
    plt.xticks(rotation=30)
    plt.tight_layout()
    st.pyplot(fig2)

st.write("---")

# --- REORDER DECISION MATRIX TABLE ---
st.subheader("📋 Replenishment Decision Control Panel")
st.write("Live procurement recommendation dashboard compiled using forecast safety parameters.")

table_rows = []
for item in all_sim_records:
    stock_code = item["StockCode"]
    desc = item["Description"]
    price = item["UnitPrice"]
    ss = item["SafetyStock"]
    rop = item["ROP"]
    inv = item["CurrentInventory"]
    
    # Formulate Action Status
    if inv <= rop:
        status_html = "<span class='status-badge status-reorder'>🚨 Reorder Immediately</span>"
    elif inv > 3.0 * rop:
        status_html = "<span class='status-badge status-over'>⚠️ Overstocked</span>"
    else:
        status_html = "<span class='status-badge status-healthy'>✓ Healthy</span>"
        
    table_rows.append({
        "SKU": stock_code,
        "Description": desc,
        "Unit Price": f"${price:.2f}",
        "Safety Stock": f"{ss} units",
        "Reorder Point (ROP)": f"{rop} units",
        "Current Inventory": f"{inv} units",
        "Action Recommendation": status_html
    })

matrix_df = pd.DataFrame(table_rows)

# Output styled HTML table
st.write(matrix_df.to_html(escape=False, index=False), unsafe_allow_html=True)
